//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierPratique_16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billet
    {
        public int N_Billet { get; set; }
        public Nullable<System.DateTime> Date_Delivrance { get; set; }
        public Nullable<int> ID_Voyage { get; set; }
    
        public virtual voyage voyage { get; set; }
    }
}
