//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierPratique_16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membre
    {
        public string pseudo { get; set; }
        public string pass { get; set; }
        public string matricule { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string service_ { get; set; }
        public string mail { get; set; }
        public string categorie { get; set; }
    }
}
