//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierPratique_16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voyage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voyage()
        {
            this.billet = new HashSet<billet>();
        }
    
        public int ID_Voyage { get; set; }
        public Nullable<System.DateTime> Date_Voyage { get; set; }
        public string Ville_Depart { get; set; }
        public string Ville_Arrive { get; set; }
        public Nullable<decimal> Duree { get; set; }
        public Nullable<int> Nbre_Voyageurs { get; set; }
        public Nullable<int> Place_libre { get; set; }
        public Nullable<decimal> Tarif { get; set; }
        public string ID_chauffeur { get; set; }
        public string Immatricule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billet> billet { get; set; }
        public virtual chauffeur chauffeur { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
